#!/bin/bash -l
#$ -S /bin/bash
#$ -l h_rt=48:00:00
#$ -l mem=2G
#$ -N pot_fit_LiNiO2
#$ -pe mpi 24 
#$ -P Gold
#$ -A Faraday_MSM_bjm
#$ -cwd
ulimit -s unlimited
ulimit -m unlimited

source $HOME/env/bin/activate

module unload compilers mpi mkl
module load compilers/gnu/4.9.2
module load mpi/openmpi/1.10.1/gnu-4.9.2
module load compilers/intel/2018/update3

./script.py
